### ISSUE TITLE
refactor doesn't work if you have sub-packages of packages with 'code'

### ISSUE THREAD

**Issue by Milraun** [stefandanaita/grpc-build#39]
Refactor generates invalid code if you have a package with code (proto-messages or enums) that has an sub-package.

You can create an repro by tweeking respose/helloworld of the test a bit:

```
syntax = "proto3";

import "grpc_build/response/sub.proto";

package grpc_build.response.helloworld;


// The response message containing the greetings
message HelloReply {
  string message = 1;
  grpc_build.response.helloworld.sub.SubEnum subEnum = 2;
}
```

the sub-package in the same directory is:

```
syntax = "proto3";

package grpc_build.response.helloworld.sub;

enum SubEnum {
  SUB = 0;
}
```

I'm new to Rust an can't fix it myself (for now). We have a big base of Proto-Models used for different languages, so that changing the protos is not an option.

Thx.

[response.zip](https://github.com/stefandanaita/grpc-build/files/11471590/response.zip)

**Comment by conradludgate** [comment]
Yeah I noticed that a while back. I got a bit too clever with the rewrite in 0.3 it seems 😓 I had an idea to fix it (by concatenating all the contents into a single file), but haven't had the time to plan it out

**Comment by tl-carlos-rosa** [comment]
I have a PR that should fix that https://github.com/stefandanaita/grpc-build/pull/44

**Comment by stefandanaita** [comment]
Thank you @tl-carlos-rosa for fixing this!
